name: Laravel 
on: 
  push:
    branches: [main] 
  pull_request: 
    branches: [main] 
       
jobs: 
  deploy: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout 
        uses: actions/checkout@v2 
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2 
        with: 
          php-version: 8.2
          extensions: mbstring, pdo, pdo_mysql, zip, fileinfo, curl, xml
      
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v1 
        with: 
          composer-options: "--ignore-platform-reqs"
      
      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync
      
      - name: Sync 
        env: 
          dest: "ubuntu@54.251.5.36:~/prod.kelasdevops.xyz/" 
        run: | 
          echo "${{secrets.DEPLOY_KEY}}" > ~/deploy_key 
          chmod 600 ~/deploy_key 
          rsync -chav --delete \ 
            -e 'ssh -i ~/deploy_key -o StrictHostKeyChecking=no' \ 
            --exclude ~/deploy_key \ 
            --exclude .git/ \ 
            --exclude .github/ \ 
            --exclude storage/ \ 
            --exclude .env \ 
            ./ ${{env.dest}}
